# 配置redis需要的信息
spring:
  redis:
    host: 118.31.113.254
    port: 6379
    password: redis9298
    database: 0
  datasource:
    url: jdbc:mysql://118.31.113.254:3306/credit_management
    username: root
    password: mysql9298
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      maxLifetime: 900000 # 设置为15分钟，单位是毫秒

mybatis:
  mapper-locations: classpath:mapper/*.xml

threadPool:
  corePoolSize: 9
  maxPoolSize: 20
  queueCapacity: 100

