# 配置redis需要的信息
spring:
  redis:
    host: 118.31.113.254
    port: 6379
    password: redis9298
    database: 0
  datasource:
    jdbcUrl: jdbc:mysql://118.31.113.254:3306/credit_management
    username: root
    password: mysql9298
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*.xml

threadPool:
  corePoolSize: 9
  maxPoolSize: 20
  queueCapacity: 100

